const {getAllProducts, getProductById, createProduct, updateProduct, deleteProduct, getProducts, createProductReview} = require('../controllers/productController');
const {isAuthenticated, allowRoles} = require('../middlewares/auth');
const express = require('express');
const productRouter = express.Router();
productRouter.get('/',isAuthenticated, getAllProducts);
productRouter.get('/search',isAuthenticated, getProducts);
productRouter.post('/create',isAuthenticated, allowRoles(['admin', 'seller']), createProduct);
productRouter.put('/:id',isAuthenticated, allowRoles(['admin', 'seller']), updateProduct);
productRouter.delete('/:id',isAuthenticated, allowRoles(['admin', 'seller']), deleteProduct);
productRouter.post('/:id/review',isAuthenticated, createProductReview);
module.exports = productRouter;