const express = require('express');
const { isAuthenticated, allowRoles } = require('../middlewares/auth');
const { updateProfile, addAddress, changePassword, deleteAddress, getAllUsers, updateUserRole, deleteUser } = require('../controllers/userController');
const userRouter = express.Router();
userRouter.use(isAuthenticated);
userRouter.put('/profile', updateProfile);
userRouter.post('/address', addAddress);
userRouter.put('/password', changePassword);
userRouter.delete('/address/:addressId', deleteAddress);
userRouter.get('/all', allowRoles('admin'), getAllUsers);
userRouter.put('/:id/role', allowRoles('admin'), updateUserRole);
userRouter.delete('/:id', allowRoles('admin'), deleteUser);
module.exports = userRouter;